kind: Pod
apiVersion: v1
metadata:
  name: thanepod
  labels:
    env: development
    class: pods
    love: devops
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Technical-Roxor; sleep 5 ; done"]
